// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 12:55:58

export interface KaryawanShowType {
  status: boolean;
  message: string;
}

export interface KaryawanShowTypeResponse {
  data: KaryawanShowType;
}

export interface KaryawanShowTypeCollection {
  data: KaryawanShowType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
