// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 14:27:07

export interface KaryawanUpdateType {
  message: string;
  exception: string;
  file: string;
  line: number;
  trace: object[];
}

export interface KaryawanUpdateTypeResponse {
  data: KaryawanUpdateType;
}

export interface KaryawanUpdateTypeCollection {
  data: KaryawanUpdateType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
