// Auto-generated by ApiResourceTyper
// Generated at: 2025-07-15 08:28:06

export interface KaryawanStoreType {
  message: string;
  exception: string;
  file: string;
  line: number;
  trace: object[];
}

export interface KaryawanStoreTypeResponse {
  data: KaryawanStoreType;
}

export interface KaryawanStoreTypeCollection {
  data: KaryawanStoreType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
