// Auto-generated by ApiResourceTyper
// Generated at: 2025-07-01 09:26:09

export interface Payroll-runStoreType {
  message: string;
  exception: string;
  file: string;
  line: number;
  trace: object[];
}

export interface Payroll-runStoreTypeResponse {
  data: Payroll-runStoreType;
}

export interface Payroll-runStoreTypeCollection {
  data: Payroll-runStoreType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
