// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 13:57:44

export interface Slip-gajiDestroyType {
  status: boolean;
  message: string;
  data: null;
}

export interface Slip-gajiDestroyTypeResponse {
  data: Slip-gajiDestroyType;
}

export interface Slip-gajiDestroyTypeCollection {
  data: Slip-gajiDestroyType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
