// Auto-generated by ApiResourceTyper
// Generated at: 2025-07-15 04:36:57

export interface Slip-gajiStoreType {
  status: boolean;
  message: string;
  data: null;
}

export interface Slip-gajiStoreTypeResponse {
  data: Slip-gajiStoreType;
}

export interface Slip-gajiStoreTypeCollection {
  data: Slip-gajiStoreType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
